site_name: Pickles
pages:
- Home: 'index.md'
- A simple start: 'StartSimple.md'
- Getting Started: 'GettingStarted.md'
- Console Application: 'ConsoleApplication.md'
- PowerShell Commandlet: 'PowerShellcommandlet.md'
- MSBuild Task: 'MSBuildTask.md'
- Experimental Features: 'ExperimentalFeatures.md'
- How To Generate Pickles Doc On Team City: 'HowToGeneratePicklesDocOnTeamCity.md'
- Integrating Test Results From SpecFlow+ Runner: 'IntegratingTestResultsFromSpecRun.md'
- Arguments:
    - Arguments: 'Arguments.md'
    - Documentation Format: 'ArgumentsDocumentationFormat.md'
    - Feature Directory: 'ArgumentsFeatureDirectory.md'
    - Output Directory: 'ArgumentsOutputDirectory.md'
    - System Under Test Name: 'ArgumentsSystemUnderTestName.md'
    - System Under Test Version: 'ArgumentsSystemUnderTestVersion.md'
    - Test Results File: 'ArgumentsTestResultsFile.md'
    - Test Results Format: 'ArgumentsTestResultsFormat.md'
    - Language: 'ArgumentsLanguage.md'
    - Include Experimental Features: 'ArgumentsIncludeExperimentalFeatures.md'
- How To Contribute: 'HowToContribute.md'
theme: readthedocs
repo_url: https://github.com/picklesdoc/docs
